services:
  db:
    image: mariadb:10.11
    container_name: sms_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sms_gateway
      MYSQL_USER: user_sms
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: sms_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    container_name: sms_frontend
    ports:
      - "4444:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  db_data: